### ISSUE TITLE
radosgw bucket usage metrics gone after created in a loop 64K buckets

### ISSUE THREAD

**Issue by Badb0yBadb0y** [blemmenes/radosgw_usage_exporter#41]
Hi,

Last week we've created for a user 64K buckets to be able to properly shard their huge amount of objects and I can see that the "radosgw_usage_bucket" metrics disappeared from 10pm that day when the mass creation happened in our octopus 15.2.17 cluster.

In the logs I don't really see anything useful.

Is there any limitation that I might have hit?

In the metrics site the beginning looks like this:
`# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="2",minor="7",patchlevel="18",version="2.7.18"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 3.37473536e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.3523328e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.69502077489e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.52
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 100000.0
# HELP radosgw_usage_bucket_quota_enabled Quota enabled for bucket
# TYPE radosgw_usage_bucket_quota_enabled gauge
# HELP radosgw_usage_bucket_objects Number of objects in bucket
# TYPE radosgw_usage_bucket_objects gauge
# HELP radosgw_usage_bucket_bytes Bucket used bytes
# TYPE radosgw_usage_bucket_bytes gauge`

Thank you

**Comment by blemmenes** [comment]
@Badb0yBadb0y I'll have to re-create this and see. I'm traveling for work this week and may not be able to get to it this week however.

Can you confirm what version of the exporter you are using?

Thanks,
Berant

**Comment by Badb0yBadb0y** [comment]
@blemmenes seems like the issue is the scrape duration, I have too many metrics and you have a 60 sec timout on metric collection.
How can I increase this 60 second metric collection please?
```
radosgw_usage_scrape_duration_seconds 60
``` 

I think if it has more time to collect the metrics it might arrive.
I use the latest version from here.

**Comment by Badb0yBadb0y** [comment]
@blemmenes is there any easy way to adjust the timeout from 60sec?

**Comment by blemmenes** [comment]
@Badb0yBadb0y Can you try the "allow_adjusting_timeouts" branch [here](https://github.com/blemmenes/radosgw_usage_exporter/tree/allow_adjusting_timeouts). It adds a '-t' timeout argument.

**Comment by Badb0yBadb0y** [comment]
The proper way would be to implement it to modify this timeout in the code
or in the run shell script add the -t option with my timeout?

**Comment by blemmenes** [comment]
There is no specific timeout in the usage exporter itself, the -t option
added in this branch is passing the supplied timeout to the requests
library that is actually handling the HTTP request.

Thanks,
Berant

**Comment by Badb0yBadb0y** [comment]
Hmm, it doesn't run, in the linux logs it complains like this:

```
 File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 526, in <module>
 File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 515, in main
 File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 64, in collect
 File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 118, in _request_data
```

Chatgpt didn't help much:

```
Check Line 118 and Surrounding Code:
Examine the _request_data method around line 118 in the script (radosgw_usage_exporter.py). Look for any syntax errors, missing or mismatched parentheses, brackets, or quotes.

Check the Method Parameters:
Verify that the parameters passed to the requests.get method on line 118 (self.session.get(url, verify=self.insecure, timeout=self.timeout, auth=S3Auth(self.access_key, self.secret_key, self.host))) are correct and in the right format.

Check Variable Values:
Print out the values of variables used in the _request_data method to ensure they have the expected values.

Check for Invalid Responses:
Check if the response from the HTTP request is valid JSON or if it's returning an unexpected response that might cause issues when trying to parse it as JSON.

Check the Network Connection:
Ensure that the host is reachable and that there are no network issues preventing the script from making the HTTP request.
```

**Comment by Badb0yBadb0y** [comment]
let me add a bit more:

```DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hkcephqa.agoda.local:8080
Traceback (most recent call last):
  File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 526, in <module>
    main()
  File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 515, in main
    args.host, args.admin_entry, args.access_key, args.secret_key, args.cluster, args.insecure, args.timeout))
  File "/usr/lib/python2.7/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/lib/python2.7/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 64, in collect
    rgw_usage = self._request_data(query='usage', args='show-summary=False')
  File "/etc/prometheus/radosgw_exporter/radosgw_usage_exporter.py", line 118, in _request_data
    self.host))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib64/python2.7/httplib.py", line 1098, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1138, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1094, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 898, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 860, in send
    self.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python2.7/site-packages/urllib3/util/connection.py", line 83, in create_connection
    sock.settimeout(timeout)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

**Comment by Badb0yBadb0y** [comment]
With this modification it started, let me test what I can collect, seems like it needs float

```
parser.add_argument(
    '-t', '--timeout',
    required=False,
    type=float,  # Ensure the timeout is a float
    help='Timeout when getting metrics',
    default=float(os.environ.get('TIMEOUT', 60)),  # Convert the default to float
)
```

**Comment by Badb0yBadb0y** [comment]
Seems like this function doesn't work yet :( It still stops after 60 sec

`radosgw_usage_scrape_duration_seconds 60.645256996154785`

What I've tried so far to add 300 instead of 60 into your code and I've also tried to add -t 300 to the run.sh but seems like ignored the value and stops collecting metrics after ~60 sec :(

Any other idea @blemmenes maybe to increase? Or I'm missing something?

**Comment by Badb0yBadb0y** [comment]
@blemmenes let me know please if this is not going to change so I'll try to figure out a second option.

**Comment by blemmenes** [comment]
FYI building my reproduction using a test cluster and creating 66k buckets under one user. I'll be able to test options tomorrow.

**Comment by Badb0yBadb0y** [comment]
thank you

**Comment by blemmenes** [comment]
@Badb0yBadb0y so typing the timeout to a float does change the timeout for me. You can see below the default of 60, which times out, then I change it to 90 and you can see it's reflected in the timeout error, then I bump it up to 300 and that completes.

Can you try with the updated branch please?

```
radosgw_usage_exporter on  allow_adjusting_timeouts [!?] via 🐍 v3.9.6 (radosgw_usage_exporter)
❯
python3 radosgw_usage_exporter.py -a bob2 -s bob2
/Users/blemmenes/github/radosgw_usage_exporter/radosgw_usage_exporter/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.127.4.167:7480
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/usage/?format=json&show-summary=False HTTP/1.1" 200 14
Request error: HTTPConnectionPool(host='10.127.4.167', port=7480): Read timed out. (read timeout=60.0)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): 10.127.4.167:7480
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&list HTTP/1.1" 200 60
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=berant&stats=True HTTP/1.1" 200 712
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob2&stats=True HTTP/1.1" 200 825
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob&stats=True HTTP/1.1" 200 702
Polling 10.127.4.167:7480. Serving at port: 9242
^C
Interrupted
radosgw_usage_exporter on  allow_adjusting_timeouts [!?] via 🐍 v3.9.6 (radosgw_usage_exporter) took 1m8s
❯
python3 radosgw_usage_exporter.py -a bob2 -s bob2 -t 90
/Users/blemmenes/github/radosgw_usage_exporter/radosgw_usage_exporter/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.127.4.167:7480
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/usage/?format=json&show-summary=False HTTP/1.1" 200 14
Request error: HTTPConnectionPool(host='10.127.4.167', port=7480): Read timed out. (read timeout=90.0)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): 10.127.4.167:7480
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&list HTTP/1.1" 200 60
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=berant&stats=True HTTP/1.1" 200 712
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob2&stats=True HTTP/1.1" 200 825
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob&stats=True HTTP/1.1" 200 702
Polling 10.127.4.167:7480. Serving at port: 9242
^C
Interrupted
radosgw_usage_exporter on  allow_adjusting_timeouts [!?] via 🐍 v3.9.6 (radosgw_usage_exporter) took 1m48s
❯
python3 radosgw_usage_exporter.py -a bob2 -s bob2 -t 300
/Users/blemmenes/github/radosgw_usage_exporter/radosgw_usage_exporter/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.127.4.167:7480
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/usage/?format=json&show-summary=False HTTP/1.1" 200 14
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/bucket/?format=json&stats=True HTTP/1.1" 200 40474623
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&list HTTP/1.1" 200 60
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=berant&stats=True HTTP/1.1" 200 712
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob2&stats=True HTTP/1.1" 200 825
DEBUG:urllib3.connectionpool:http://10.127.4.167:7480 "GET /admin/user/?format=json&uid=bob&stats=True HTTP/1.1" 200 702
Polling 10.127.4.167:7480. Serving at port: 9242
```

**Comment by Badb0yBadb0y** [comment]
I'm going to test now.

**Comment by blemmenes** [comment]
Yeah I've run into that too. I've had to tweak the harpoxy `server timeout`.

Sounds good, I'll merge this branch into master and push it out.

Thanks,
Berant

**Comment by blemmenes** [comment]
Merged in #42 closing.
